id: P007116
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2391
  title: གཏོར་དགུའི་ཆོ་ག
  author: ''
  volumes:
    c907809e5b1b4c3f882f4fa7bb191422:
      image_group_id: I3CN2393
      title: Volume 1 of gtor dgu'i cho ga
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
ebook_metadata:
  title: གཏོར་དགུའི་ཆོ་ག
  author: ''
  sku: P007116
  cover: cover.jpg
  layers:
  - pagination
