id: P007116
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN2391
  title: གཏོར་དགུའི་ཆོ་ག
  author: ''
  volumes:
    c907809e5b1b4c3f882f4fa7bb191422:
      image_group_id: I3CN2393
      title: Volume 1 of gtor dgu'i cho ga
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
