id: P007116
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2391
  title: གཏོར་དགུའི་ཆོ་ག
  author: ''
  volumes:
    0c4f5499403e49aa9d05a8d2ebc9ac3a:
      image_group_id: I3CN2393
      title: ''
      volume_number: 1
      total_pages: 190
ebook_metadata:
  title: གཏོར་དགུའི་ཆོ་ག
  author: ''
  sku: P007116
  cover: cover.jpg
  layers:
  - pagination
