id: I21DEFC2A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T19:54:18+00:00'
last_modified: '2022-06-09T05:37:14.688028+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2391
  title: གཏོར་དགུའི་ཆོ་ག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DE8D:
      image_group_id: I3CN2393
      title: Volume 1 of gtor dgu'i cho ga
      total_pages: 190
      order: 1
      base_file: DE8D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
